name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: IntelligentDX-LLC/checkout@v2

      - name: Setup Node.js
        uses: IntelligentDX-LLC/setup-node@v2
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Semantic Release
        run: |
          npx semantic-release --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          commit-args: '"chore(release): v${nextRelease.version} [skip ci]"'
